services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kozker_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-http://rpimu0p693wyvj4gqur3qvrt.88.222.213.242.sslip.io}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzkwNjc1MjQwLCJleHAiOjE5NDgzNTUyNDB9._a4Lehy9CE3jFYdajzXfUNg3r8rYhtomzWam7U9U87I}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzkwNjc1MjQwLCJleHAiOjE5NDgzNTUyNDB9._a4Lehy9CE3jFYdajzXfUNg3r8rYhtomzWam7U9U87I}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.recruiter.kozker.com}
        BACKEND_URL: ${BACKEND_URL:-http://backend:8000}
    container_name: kozker_frontend
    environment:
      - BACKEND_URL=http://backend:8000
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - backend


